export const artists = [
    "stadio",
    "andrea bocelli",
    "anna oxa",
    "laura pausini",
    "alice",
    "mango",
    "max gazzè",
    "enrico ruggeri",
    "coma_cose",
    "matia bazar",
    "le vibrazioni",
    "elisa",
    "diodato",
    "eros ramazzotti",
    "gianluca grignani",
    "mietta",
    "colapesce",
    "la rappresentante di lista",
    "nek",
    "bugo",
    "renato zero",
    "fiorella mannoia",
    "noemi",
    "patty pravo",
    "ex-otago",
    "lucio dalla",
    "zucchero",
    "francesca michielin",
    "lo stato sociale",
    "giorgia",
    "ron",
    "annalisa",
    "umberto tozzi",
    "francesco gabbani",
    "nicola di bari",
    "eduardo de crescenzo",
    "pooh",
    "alex britti",
    "fiordaliso",
    "daniele silvestri",
    "jalisse",
    "adriano celentano",
    "domenico modugno",
    "nada",
    "al bano e romina power",
    "riccardo cocciante",
    "loretta goggi",
    "ermal meta",
    "ivana spagna",
    "roberto vecchioni",
    "loredana bertè",
    "luigi tenco",
    "vasco rossi",
    "levante",
    "ornella vanoni",
    "mia martini",
    "enzo carella",
    "fabrizio moro",
    "il volo",
    "arisa",
    "luis miguel",
    "negramaro",
    "zero assoluto",
    "sergio endrigo",
    "francesca alotta",
    "rino gaetano",
    "fausto leali",
    "amedeo minghi",
    "morgan",
    "the randy jackson band",
    "tosca"

]
